version: "3.8"

services:

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lock_in
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  web:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

volumes:
  db-store:
